[experiment]
tasks = ["cifar10"]
seed = 42
device = "cuda:0"

[model]
arch = "resnet18_cifar"
num_classes = 10

[data]
batch_size = 256
num_workers = 0
aug = true
cutout = true
n_holes = 1
cutout_length = 16

[optimizer]
name = "Hadron"
lr = 0.001
momentum = 0.9
stat_decay = 0.95
damping = 0.001
kl_clip = 0.001
weight_decay = 0.0005
TCov = 10
TInv = 100
muon_momentum = 0.95

[scheduler]
name = "cosine"     # 对齐Muon的scheduler
T_max = 200

[train]
epochs = 10
log_every = 10
ckpt_every = 10