[experiment]
task = "cifar10"
seed = 42
device = "cuda"

[model]
arch = "resnet18_cifar"
num_classes = 10

[data]
batch_size = 256
num_workers = 5
aug = true
cutout = true
n_holes = 1
cutout_length = 16

[optimizer]
name = "F3EL"
lr = 0.001
weight_decay = 5e-4
loss_scaling = true # 启用损失缩放

[scheduler]
name = "cosine"
T_max = 200

[train]
epochs = 200
log_every = 10
ckpt_every = 50

[early_stop]
patience = 10
threshold = 0.3